<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
	<OutputPath>..\Heavy Liquid Shuttle\bin\Debug\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.4.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Heavy Liquid Shuttle\HeavyLiquidShuttle.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin64_Data\Managed\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="BadHygiene">
      <HintPath>..\..\..\..\..\..\Games\Rimworld\Mods\Dubs\1.6\Assemblies\BadHygiene.dll</HintPath>
    </Reference>
    <Reference Include="Rimefeller">
      <HintPath>..\..\..\..\..\..\Games\Rimworld\Mods\Rimefeller\1.6\Assemblies\Rimefeller.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin64_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
